---
title: "Superbowl_Ads"
author: "Ty Lacy"
date: "7/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("tuber")
pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, ggvis, httr, lubridate,
               plotly, rio, rmarkdown, shiny, stringr, tidyr)
library(tidyverse)
library(tuber)
library(rvest)
library(httr)

```
```{r}
# load data
youtube <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-02/youtube.csv')
```
```{r}
# remove na and get like percentages
reviews <- youtube %>% 
  drop_na() %>% 
  mutate(like_percentage = like_count/view_count, dislike_percentage = dislike_count/view_count,
         comment_percentage = comment_count/view_count) %>% 
  select(year, brand, patriotic, celebrity, danger, animals, use_sex, like_percentage, 
         dislike_percentage, comment_percentage)

```
```{r}
# group by brand
review_sum <- reviews %>% 
  group_by(brand) %>% 
  summarise(like_mean = mean(like_percentage), dislike_mean = mean(dislike_percentage),
            comment_mean = mean(comment_percentage)) %>% 
  select(brand, like_mean, dislike_mean, comment_mean)
```

#plots
```{r}

(brand_plot <- review_sum %>% 
  ggplot(aes(x = brand, y = like_mean, fill = brand)) +
  geom_col() + 
  coord_flip() +
  theme_classic()) 

```
```{r}
(brand_like <- reviews %>% 
  ggplot(aes(x = brand, y = like_percentage, fill = brand)) +
  geom_boxplot(show.legend = FALSE) + 
  theme_classic()) 
(brand_dislike <- reviews %>% 
  ggplot(aes(x = brand, y = dislike_percentage, fill = brand)) +
  geom_boxplot(show.legend = FALSE) + 
  theme_classic()) 
(brand_comment <- reviews %>% 
  ggplot(aes(x = brand, y = comment_percentage, fill = brand)) +
  geom_boxplot(show.legend = FALSE) + 
  theme_classic()) 
```